// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace monoBooks {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("DetailsViewController")]
	public partial class DetailsViewController {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UILabel __mt_author;
		
		private MonoTouch.UIKit.UILabel __mt_bookTitle;
		
		private MonoTouch.UIKit.UITextView __mt_desc;
		
		private MonoTouch.UIKit.UILabel __mt_price;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("author")]
		private MonoTouch.UIKit.UILabel author {
			get {
				this.__mt_author = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("author")));
				return this.__mt_author;
			}
			set {
				this.__mt_author = value;
				this.SetNativeField("author", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("bookTitle")]
		private MonoTouch.UIKit.UILabel bookTitle {
			get {
				this.__mt_bookTitle = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("bookTitle")));
				return this.__mt_bookTitle;
			}
			set {
				this.__mt_bookTitle = value;
				this.SetNativeField("bookTitle", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("desc")]
		private MonoTouch.UIKit.UITextView desc {
			get {
				this.__mt_desc = ((MonoTouch.UIKit.UITextView)(this.GetNativeField("desc")));
				return this.__mt_desc;
			}
			set {
				this.__mt_desc = value;
				this.SetNativeField("desc", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("price")]
		private MonoTouch.UIKit.UILabel price {
			get {
				this.__mt_price = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("price")));
				return this.__mt_price;
			}
			set {
				this.__mt_price = value;
				this.SetNativeField("price", value);
			}
		}
	}
}
